services:
  mongodb:
    image: mongo:latest
    container_name: jams-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - ./data/db:/data/db

  products-app:
    build:
      context: .
      dockerfile: Dockerfile.products
    container_name: jams-products-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=${MONGO_URL}
    networks:
      - jams-network

networks:
  jams-network:
    driver: bridge