services:
  mongodb:
    image: mongo:latest
    container_name: jams-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - ./data/db:/data/db

  mysql:
    image: mysql:9.6.0
    container_name: jams-mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  products-app:
    build:
      context: .
      dockerfile: Dockerfile.products
    container_name: jams-products
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=${MONGO_URL}
    networks:
      - jams-network

  orders-app:
    build:
      context: .
      dockerfile: Dockerfile.orders
    container_name: jams-orders
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      - MYSQL_URL=${MYSQL_URL}
    networks:
      - jams-network

  inventory-app:
    build:
      context: .
      dockerfile: Dockerfile.inventory
    container_name: jams-inventory
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      - MYSQL_URL=${MYSQL_URL}
    networks:
      - jams-network

networks:
  jams-network:
    driver: bridge